"""Tests for the resumable pipeline runner."""

from __future__ import annotations

import json
from pathlib import Path

from db.repositories import FileRepository
from db.session import Database
from models.enums import PipelineStage, RunnerStatus
from services.ai_classifier import AIClassificationResult
from services.pipeline_runner import (
    PipelineRunner,
    reset_pipeline_handlers,
    set_stage_handler,
)


def test_runner_completes_all_stages(tmp_path: Path) -> None:
    md = tmp_path / "a.md"
    # Content must exceed the small-file lane threshold (260 chars) and contain no
    # relevance keywords so the file lands on the relevance gate (fallback) path.
    _GENERIC = (
        "This document was generated by the automated test harness to confirm each stage "
        "of execution completes in sequence. The content here is intentionally neutral and "
        "free of any domain-specific signals. No business, technical, or career-related "
        "terms appear in this block of text at all."
    )
    md.write_text(_GENERIC, encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(md.resolve()), display_name="a.md")

    norm = tmp_path / "normalized"
    exports = tmp_path / "exports"
    out = PipelineRunner(d, normalized_work_dir=norm, export_root=exports).run()
    assert out.files_started == 1
    assert out.files_finished_ok == 1
    assert out.files_marked_failed == 0

    rec = files.get_by_path(str(md.resolve()))
    assert rec is not None
    assert rec.runner_status == RunnerStatus.COMPLETED.value
    assert rec.pipeline_next_stage is None
    assert rec.last_error is None
    assert rec.stage_checkpoint is not None
    payload = json.loads(rec.stage_checkpoint)
    assert payload["normalized_path"]
    assert isinstance(payload["chunks"], list)
    assert isinstance(payload["chunk_metadata"], list)
    assert payload["chunk_count"] == len(payload["chunks"])
    assert payload["export_profile"] == "anythingllm"
    assert payload.get("workspace") is None
    assert payload["category"] == "other"
    assert payload["matched_by"] == "fallback"
    assert payload["review_required"] is True
    assert payload["classification_reason"]
    assert Path(payload["export_source_path"]).is_file()
    assert (exports / "anythingllm" / "files_manifest.csv").is_file()
    assert (exports / "anythingllm" / "chunks_manifest.json").is_file()
    conn = d.connect()
    job_rows = conn.execute(
        "SELECT id, kind, status, result_json FROM jobs ORDER BY id DESC LIMIT 1"
    ).fetchall()
    assert len(job_rows) == 1
    jr = job_rows[0]
    assert jr["kind"] == "pipeline_run"
    assert jr["status"] == "completed"
    result_payload = json.loads(str(jr["result_json"]))
    assert result_payload["files_started"] == 1
    assert result_payload["files_finished_ok"] == 1


def test_runner_resumes_failed_file(tmp_path: Path) -> None:
    f = tmp_path / "b.txt"
    f.write_text("content", encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(f.resolve()), display_name="b.txt")

    def fail_once(record, stage: PipelineStage) -> None:
        if stage == PipelineStage.CLASSIFIED:
            raise RuntimeError("temporary")

    set_stage_handler(PipelineStage.CLASSIFIED, fail_once)
    try:
        out1 = PipelineRunner(
            d,
            normalized_work_dir=tmp_path / "n1",
            export_root=tmp_path / "e1",
        ).run()
        assert out1.files_marked_failed == 1
        rec = files.get_by_path(str(f.resolve()))
        assert rec is not None
        assert rec.runner_status == RunnerStatus.FAILED.value
        assert rec.pipeline_next_stage == PipelineStage.CLASSIFIED.value

        reset_pipeline_handlers()
        out2 = PipelineRunner(
            d,
            normalized_work_dir=tmp_path / "n2",
            export_root=tmp_path / "e2",
        ).run()
        assert out2.files_finished_ok == 1
        again = files.get_by_path(str(f.resolve()))
        assert again is not None
        assert again.runner_status == RunnerStatus.COMPLETED.value
    finally:
        reset_pipeline_handlers()


def test_max_files_limits_batch(tmp_path: Path) -> None:
    (tmp_path / "1.md").write_text("# A\n", encoding="utf-8")
    (tmp_path / "2.md").write_text("# B\n", encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str((tmp_path / "1.md").resolve()), display_name="1.md")
    files.insert(path=str((tmp_path / "2.md").resolve()), display_name="2.md")

    out = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "norm",
        export_root=tmp_path / "exp",
    ).run(max_files=1)
    assert out.files_started == 1
    assert out.files_finished_ok == 1

    out2 = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "norm",
        export_root=tmp_path / "exp",
    ).run(max_files=1)
    assert out2.files_started == 1
    assert out2.files_finished_ok == 1


def test_runner_queues_are_distinct_by_export_profile(tmp_path: Path) -> None:
    md = tmp_path / "profile-queue.md"
    md.write_text("# profile queue\n", encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(md.resolve()), display_name="profile-queue.md")

    out_anything = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "norm_anything",
        export_root=tmp_path / "exports_anything",
        export_profile="anythingllm",
    ).run()
    assert out_anything.files_finished_ok == 1

    out_openwebui = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "norm_openweb",
        export_root=tmp_path / "exports_openweb",
        export_profile="open_webui",
    ).run()
    assert out_openwebui.files_finished_ok == 1

    rec = files.get_by_path(str(md.resolve()))
    assert rec is not None
    assert rec.runner_status == RunnerStatus.COMPLETED.value


def test_ollama_ai_only_unclassified_uses_ai_and_persists(tmp_path: Path) -> None:
    md = tmp_path / "draft-notes.md"
    # Content must exceed the small-file lane threshold (260 chars) and contain no
    # relevance keywords so the file lands on the relevance gate (fallback) path,
    # which is what triggers AI in ai_only_unclassified mode.
    _GENERIC = (
        "This document was generated by the automated test harness to confirm each stage "
        "of execution completes in sequence. The content here is intentionally neutral and "
        "free of any domain-specific signals. No business, technical, or career-related "
        "terms appear in this block of text at all."
    )
    md.write_text(_GENERIC, encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(md.resolve()), display_name="draft-notes.md")
    cfg = tmp_path / "classification_rules.json"
    cfg.write_text(
        json.dumps(
            {
                "enable_ollama": True,
                "ollama_model": "fake",
                "ai_mode": "ai_only_unclassified",
                "FORCE_RULES": [],
                "COMPANY_MAP": {},
                "PROJECT_MAP": {},
                "CODE_EXT": {},
            }
        ),
        encoding="utf-8",
    )

    class FakeAI:
        def classify(self, *, file_path, file_name, preview_text):
            del file_path, file_name, preview_text
            return AIClassificationResult(
                workspace="Career_Portfolio",
                subfolder="ai",
                confidence=0.93,
                doc_type="portfolio",
                reasoning="mock",
            )

    out = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "normalized",
        export_root=tmp_path / "exports",
        classification_config_path=cfg,
        ai_classifier=FakeAI(),
    ).run()
    assert out.files_finished_ok == 1
    rec = files.get_by_path(str(md.resolve()))
    assert rec is not None
    assert rec.ai_used is True
    assert rec.matched_by == "ollama"
    assert rec.classification_reason is not None and "Ollama" in rec.classification_reason
    assert rec.content_hash


def test_ollama_ai_all_does_not_override_force_rule(tmp_path: Path) -> None:
    md = tmp_path / "resume_for_job.md"
    md.write_text("experience", encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(md.resolve()), display_name="resume_for_job.md")
    cfg = tmp_path / "classification_rules.json"
    cfg.write_text(
        json.dumps({"enable_ollama": True, "ollama_model": "fake", "ai_mode": "ai_all"}),
        encoding="utf-8",
    )

    class FakeAI:
        def classify(self, *, file_path, file_name, preview_text):
            del file_path, file_name, preview_text
            return AIClassificationResult(
                workspace="Archive",
                subfolder="",
                confidence=0.99,
                doc_type="reference",
                reasoning="ai would pick this",
            )

    out = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "normalized",
        export_root=tmp_path / "exports",
        classification_config_path=cfg,
        ai_classifier=FakeAI(),
    ).run()
    assert out.files_finished_ok == 1
    rec = files.get_by_path(str(md.resolve()))
    assert rec is not None
    assert rec.matched_by == "force_rule"
    assert rec.ai_used is False
    assert rec.classification_reason and (
        "resume" in rec.classification_reason.lower() or "FORCE_RULES" in rec.classification_reason
    )


def test_ollama_failure_falls_back_safely(tmp_path: Path) -> None:
    md = tmp_path / "fallback.md"
    # Content must exceed the small-file lane threshold (260 chars) and contain no
    # relevance keywords so the file lands on the relevance gate (fallback) path.
    # When AI then fails, rules_decision.matched_by is already 'fallback'.
    _GENERIC = (
        "This document was generated by the automated test harness to confirm each stage "
        "of execution completes in sequence. The content here is intentionally neutral and "
        "free of any domain-specific signals. No business, technical, or career-related "
        "terms appear in this block of text at all."
    )
    md.write_text(_GENERIC, encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(md.resolve()), display_name="fallback.md")
    cfg = tmp_path / "classification_rules.json"
    cfg.write_text(
        json.dumps({"enable_ollama": True, "ollama_model": "fake", "ai_mode": "ai_all"}),
        encoding="utf-8",
    )

    class FailingAI:
        def classify(self, *, file_path, file_name, preview_text):
            del file_path, file_name, preview_text
            raise RuntimeError("boom")

    out = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "normalized",
        export_root=tmp_path / "exports",
        classification_config_path=cfg,
        ai_classifier=FailingAI(),
    ).run()
    assert out.files_finished_ok == 1
    rec = files.get_by_path(str(md.resolve()))
    assert rec is not None
    assert rec.ai_used is False
    assert rec.matched_by == "fallback"


def test_ollama_cache_by_content_hash(tmp_path: Path) -> None:
    f1 = tmp_path / "same1.md"
    f2 = tmp_path / "same2.md"
    f1.write_text("same content", encoding="utf-8")
    f2.write_text("same content", encoding="utf-8")
    d = Database(Path(":memory:"))
    d.connect()
    files = FileRepository(d)
    files.insert(path=str(f1.resolve()), display_name="same1.md", sha256="h1")
    files.insert(path=str(f2.resolve()), display_name="same2.md", sha256="h1")
    cfg = tmp_path / "classification_rules.json"
    cfg.write_text(
        json.dumps(
            {
                "enable_ollama": True,
                "ollama_model": "fake",
                "ai_mode": "ai_all",
                "FORCE_RULES": [],
                "COMPANY_MAP": {},
                "PROJECT_MAP": {},
                "CODE_EXT": {},
            }
        ),
        encoding="utf-8",
    )

    class CountingAI:
        def __init__(self):
            self.calls = 0

        def classify(self, *, file_path, file_name, preview_text):
            del file_path, file_name, preview_text
            self.calls += 1
            return AIClassificationResult(
                workspace="Archive",
                subfolder="cached",
                confidence=0.88,
                doc_type="reference",
                reasoning="first-call",
            )

    fake = CountingAI()
    runner = PipelineRunner(
        d,
        normalized_work_dir=tmp_path / "normalized",
        export_root=tmp_path / "exports",
        classification_config_path=cfg,
        ai_classifier=fake,
    )
    out = runner.run(max_files=2)
    assert out.files_finished_ok == 2
    assert fake.calls == 1
